# Streamlit Cloud 密钥配置文件
# 在 Streamlit Cloud 部署时，需要在 App settings > Secrets 中配置以下变量

# API 后端 URL - 替换为你的 Render 后端 URL
API_BASE_URL = "https://your-render-app.onrender.com"

# 可选：其他配置
# MAX_UPLOAD_SIZE = 10
# TIMEOUT_SECONDS = 30